#!/usr/bin/env python
"""
Using GTK+3 to implement a GUI application.
This application could randomly remove words
of an article and check the integrity of
your filling result.
"""
from gi.repository import Gtk


class HellowWorldGTK(object):
    """This is a Hello World GTK application"""

    def __init__(self):
        # layout generated by glade
        layout_filename = "layout.xml"
        builder = Gtk.Builder()
        builder.add_from_file(layout_filename)
        #builder.connect_signals(self)

        self.window = builder.get_object("window1")
        if self.window:
            self.window.connect("destroy", Gtk.main_quit)
        self.window.show_all()

if __name__ == "__main__":
    hwg = HellowWorldGTK()
    Gtk.main()
